### ISSUE TITLE
Build configuration

### ISSUE THREAD

**Issue by ioma8** [Apaczer/eduke32#1]
Hello. I wanted to build this modified eduke32 myself. I am trying the script mkduke_miyoo.sh but I am getting errors. I see you are adding /opt/miyoo/bin into PATH in the build script. Does this mean I need to have binaries of miyoo firmware in this directory? Overall what are the prerequisities for making this build?

**Comment by Apaczer** [comment]
Hi,
Remember that you're cross-compiling to a different architecture so u need specific SDK for that platform and there is unwritten rule in MiyooCFW community that you usually place it at /opt/miyoo/ dir. For a working SDK's see submodules pack in e.g. https://github.com/TriForceX/MiyooCFW/actions/runs/6795425725 or grab the old toolchain from: https://github.com/steward-fu/archives/releases/download/miyoo/env_toolchain.7z
